apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logstash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "logstash.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: logstash
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: tcp
          containerPort: 5000
          protocol: TCP
        - name: beats
          containerPort: 5044
          protocol: TCP
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ .Values.elasticsearch.host | quote }}
        - name: ELASTICSEARCH_PORT
          value: {{ .Values.elasticsearch.port | quote }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers | quote }}
        - name: LS_JAVA_OPTS
          value: "-Xmx512m -Xms512m"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: config
        configMap:
          name: {{ include "logstash.fullname" . }}-config

