apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: tcp
    protocol: TCP
    name: tcp
  - port: {{ .Values.service.tcpPort }}
    targetPort: beats
    protocol: TCP
    name: beats
  selector:
    {{- include "logstash.selectorLabels" . | nindent 4 }}

