apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zipkin.fullname" . }}
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zipkin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zipkin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP
          env:
            - name: STORAGE_TYPE
              value: {{ .Values.storage.type | quote }}
            {{- if eq .Values.storage.type "elasticsearch" }}
            - name: ES_HOSTS
              value: {{ .Values.storage.elasticsearch.hosts | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}

