{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prometheus.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "prometheus.fullname" . }}
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time={{ .Values.prometheus.retention }}'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.enable-lifecycle'
          ports:
            - name: http
              containerPort: {{ .Values.prometheus.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: storage
              mountPath: /prometheus
          {{- if .Values.prometheus.startupProbe }}
          startupProbe:
            {{- toYaml .Values.prometheus.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.prometheus.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.prometheus.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.prometheus.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.prometheus.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "prometheus.fullname" . }}-config
        - name: storage
          {{- if .Values.prometheus.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "prometheus.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}

