{{- if and .Values.prometheus.enabled .Values.prometheus.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus.fullname" . }}-pvc
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.prometheus.storage.storageClassName }}
  storageClassName: {{ .Values.prometheus.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
{{- end }}

