apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange.fullname" . }}-config
  labels:
    {{- include "exchange.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: exchange
      autoconfigure:
        exclude:
          - org.springframework.cloud.consul.discovery.ConsulDiscoveryClientConfiguration
          - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
          - org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistryAutoConfiguration
          - org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration
      cloud:
        consul:
          enabled: false
          discovery:
            enabled: false
          config:
            enabled: false
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
    
    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
    
    oauth2:
      client:
        id: ${OAUTH2_CLIENT_ID:exchange-service}
        secret: ${OAUTH2_CLIENT_SECRET:exchange-secret-key-12345}
    
    server:
      port: 8084
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers,refresh
    
    logging:
      level:
        ru.rpovetkin.exchange: DEBUG
        org.springframework.security: DEBUG

