spring:
  application:
    name: transfer
  security:
    oauth2:
      client:
        registration:
          transfer-service:
            client-id: ${OAUTH2_CLIENT_ID:transfer-service}
            client-secret: ${OAUTH2_CLIENT_SECRET:transfer-secret-key-12345}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/token}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,refresh

services:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://bankapp-accounts:8081}
  notifications:
    url: ${NOTIFICATIONS_SERVICE_URL:http://bankapp-notifications:8087}
  exchange:
    url: ${EXCHANGE_SERVICE_URL:http://bankapp-exchange:8084}
  blocker:
    url: ${BLOCKER_SERVICE_URL:http://bankapp-blocker:8086}
