spring:
  application:
    name: transfer
  security:
    oauth2:
      client:
        registration:
          transfer-service:
            client-id: ${OAUTH2_CLIENT_ID:transfer-service}
            client-secret: ${OAUTH2_CLIENT_SECRET:transfer-secret-key-12345}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/token}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      notifications: account-notifications

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,refresh

services:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://accounts:8081}
  exchange:
    url: ${EXCHANGE_SERVICE_URL:http://exchange:8084}
  blocker:
    url: ${BLOCKER_SERVICE_URL:http://blocker:8086}
