apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer.fullname" . }}-config
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: transfer
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        template:
          observation-enabled: true
        topics:
          notifications: account-notifications
    
    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
    
    oauth2:
      client:
        id: ${OAUTH2_CLIENT_ID:transfer-service}
        secret: ${OAUTH2_CLIENT_SECRET:transfer-secret-key-12345}
    
    services:
      accounts:
        url: ${ACCOUNTS_SERVICE_URL:http://bankapp-accounts:8081}
      notifications:
        url: ${NOTIFICATIONS_SERVICE_URL:http://bankapp-notifications:8087}
      exchange:
        url: ${EXCHANGE_SERVICE_URL:http://bankapp-exchange:8084}
      blocker:
        url: ${BLOCKER_SERVICE_URL:http://bankapp-blocker:8086}
    
    server:
      port: 8083
      forward-headers-strategy: native
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers,metrics,prometheus,traces
      
      # Tracing configuration
      tracing:
        sampling:
          probability: ${TRACING_SAMPLE_RATE:1.0}
        propagation:
          type: b3
      
      # Zipkin exporter configuration
      zipkin:
        tracing:
          endpoint: ${ZIPKIN_BASE_URL:http://bankapp-zipkin:9411}/api/v2/spans
    
    logging:
      level:
        ru.rpovetkin.transfer: INFO
        org.springframework.kafka: INFO
        root: INFO
      pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
