apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer.fullname" . }}-config
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: transfer
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
    
    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
    
    oauth2:
      client:
        id: ${OAUTH2_CLIENT_ID:transfer-service}
        secret: ${OAUTH2_CLIENT_SECRET:transfer-secret-key-12345}
    
    services:
      accounts:
        url: ${ACCOUNTS_SERVICE_URL:http://bankapp-accounts:8081}
      notifications:
        url: ${NOTIFICATIONS_SERVICE_URL:http://bankapp-notifications:8085}
      exchange:
        url: ${EXCHANGE_SERVICE_URL:http://bankapp-exchange:8084}
      blocker:
        url: ${BLOCKER_SERVICE_URL:http://bankapp-gateway:8088}
      gateway:
        url: ${GATEWAY_SERVICE_URL:http://bankapp-gateway:8088}
    
    server:
      port: 8083
      forward-headers-strategy: native
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers

