apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer.fullname" . }}-secret
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth2-client-secret: {{ .Values.oauth2ClientSecret | default "transfer-secret-key-12345" | quote }}

