apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-ui.fullname" . }}-config
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: front-ui
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
    
    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
    
    oauth2:
      client:
        id: ${OAUTH2_CLIENT_ID:front-ui-service}
        secret: ${OAUTH2_CLIENT_SECRET:front-ui-secret-key-12345}
    
    accounts:
      service:
        url: ${ACCOUNTS_SERVICE_URL:http://bankapp-accounts:8081}
    
    cash:
      service:
        url: ${CASH_SERVICE_URL:http://bankapp-cash:8082}
    
    transfer:
      service:
        url: ${TRANSFER_SERVICE_URL:http://bankapp-transfer:8083}
    
    exchange:
      service:
        url: ${EXCHANGE_SERVICE_URL:http://bankapp-exchange:8084}
    
    server:
      forward-headers-strategy: native
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers
