apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-ui.fullname" . }}-secret
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth2-client-secret: {{ .Values.oauth2ClientSecret | default "front-ui-secret-key-12345" | quote }}

