spring:
  application:
    name: accounts
  autoconfigure:
    exclude:
      - org.springframework.cloud.consul.discovery.ConsulDiscoveryClientConfiguration
      - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
      - org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistryAutoConfiguration
      - org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankapp}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_ID:accounts-service}
            client-secret: ${OAUTH2_CLIENT_SECRET:accounts-secret-key-12345}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/token}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}

oauth2:
  client:
    id: ${OAUTH2_CLIENT_ID:accounts-service}
    secret: ${OAUTH2_CLIENT_SECRET:accounts-secret-key-12345}

gateway:
  service:
    url: ${GATEWAY_SERVICE_URL:http://bankapp-gateway:8080}
    
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,refresh
