apiVersion: v2
name: accounts
description: A Helm chart for the accounts microservice
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"
apiVersion: v2
name: accounts
description: A Helm chart for the accounts microservice
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"

