spring:
  application:
    name: front-ui

accounts:
  service:
    url: http://${ACCOUNTS_HOST:localhost}:${ACCOUNTS_PORT:8081}

cash:
  service:
    url: ${CASH_SERVICE_URL:http://localhost:8082}

exchange:
  service:
    url: ${EXCHANGE_SERVICE_URL:http://localhost:8084}
