spring:
  application:
    name: front-ui
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
  cloud:
    compatibility-verifier:
      enabled: false
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        service-name: front-ui
        instance-id: front-ui-1
        hostname: front-ui-app

accounts:
  service:
    url: http://accounts

cash:
  service:
    url: http://cash

transfer:
  service:
    url: http://transfer

exchange:
  service:
    url: http://exchange
