apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-secret
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth2-client-secret: {{ .Values.oauth2ClientSecret | default "gateway-secret-key-12345" | quote }}

