{{- if .Values.kafkaUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafkaui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kafkaUI.service.type }}
  ports:
  - port: {{ .Values.kafkaUI.service.port }}
    targetPort: {{ .Values.kafkaUI.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "kafkaui.selectorLabels" . | nindent 4 }}
{{- end }}
