apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: {{ .Values.kafka.service.targetPort }}
    protocol: TCP
    name: kafka
  - port: {{ .Values.kafka.service.controllerPort }}
    targetPort: {{ .Values.kafka.service.controllerPort }}
    protocol: TCP
    name: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
