apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker.fullname" . }}-config
  labels:
    {{- include "blocker.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: blocker
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
    
    logging:
      level:
        ru.rpovetkin.blocker: INFO
        root: INFO
      pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers,metrics,prometheus,traces
      
      # Metrics configuration
      metrics:
        export:
          prometheus:
            enabled: true
        distribution:
          percentiles-histogram:
            http.server.requests: true
        tags:
          application: ${spring.application.name}
          service: blocker
      
      # Tracing configuration
      tracing:
        sampling:
          probability: ${TRACING_SAMPLE_RATE:1.0}
      
      # Zipkin exporter configuration
      zipkin:
        tracing:
          endpoint: ${ZIPKIN_BASE_URL:http://bankapp-zipkin:9411}/api/v2/spans
    
    # Конфигурация лимитов безопасности
    blocker:
      limits:
        max-transfer-amount: 50000

