apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" . }}-secret
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth2-client-secret: {{ .Values.oauth2ClientSecret | default "cash-secret-key-12345" | quote }}

