apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}-config
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: accounts
      datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankapp}
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-id: ${OAUTH2_CLIENT_ID:accounts-service}
                client-secret: ${OAUTH2_CLIENT_SECRET:accounts-secret-key-12345}
                authorization-grant-type: client_credentials
                scope: openid,profile,email
                provider: keycloak
            provider:
              keycloak:
                token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/token}
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
    
    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
    
    oauth2:
      client:
        id: ${OAUTH2_CLIENT_ID:accounts-service}
        secret: ${OAUTH2_CLIENT_SECRET:accounts-secret-key-12345}
    
    services:
      notifications:
        url: ${NOTIFICATIONS_SERVICE_URL:http://bankapp-notifications:8087}
    
    server:
      port: 8081
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers,refresh

