apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts.fullname" . }}-secret
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth2-client-secret: {{ .Values.oauth2ClientSecret | default "accounts-secret-key-12345" | quote }}

