spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      client:
        registration:
          exchange-generator-service:
            client-id: ${OAUTH2_CLIENT_ID:exchange-generator-service}
            client-secret: ${OAUTH2_CLIENT_SECRET:exchange-generator-secret-key-12345}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/token}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}

server:
  port: 8085

exchange:
  service:
    url: ${EXCHANGE_SERVICE_URL:http://exchange-app:8084}

logging:
  level:
    ru.rpovetkin.exchange_generator: DEBUG
    org.springframework.security: DEBUG