# Default values for front-ui
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: bankapp/front-ui
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# OAuth2 client secret (sensitive data)
oauth2ClientSecret: "front-ui-secret-key-12345"

env:
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs"
  OAUTH2_CLIENT_ID: "front-ui-service"
  ACCOUNTS_SERVICE_URL: "http://accounts:8081"
  CASH_SERVICE_URL: "http://cash:8082"
  TRANSFER_SERVICE_URL: "http://transfer:8083"
  EXCHANGE_SERVICE_URL: "http://exchange:8084"
  ZIPKIN_BASE_URL: "http://zipkin:9411"
  ZIPKIN_ENABLED: "true"
  TRACING_SAMPLE_RATE: "1.0"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30  # Максимум: 30 + (10 * 30) = 330 секунд (5.5 минут)

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 150  # Начинаем проверять после успешного старта
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
