apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange-generator.fullname" . }}-secret
  labels:
    {{- include "exchange-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth2-client-secret: {{ .Values.oauth2ClientSecret | default "exchange-generator-secret-key-12345" | quote }}

