apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications.fullname" . }}-config
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: notifications
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers
    
    logging:
      level:
        ru.rpovetkin.notifications: DEBUG
        org.springframework.messaging: DEBUG
        org.springframework.web.socket: DEBUG
        root: INFO
      pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

