apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications.fullname" . }}-secret
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
type: Opaque
data:
  # Empty for now, can be used for sensitive configuration in the future

