server:
  port: 8087

spring:
  application:
    name: notifications
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notifications-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topics:
      notifications: account-notifications

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

logging:
  level:
    ru.rpovetkin.notifications: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
