server:
  port: 8087

spring:
  application:
    name: notifications
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}

logging:
  level:
    ru.rpovetkin.notifications: INFO
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
