server:
  port: 8087

spring:
  application:
    name: notifications
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notifications-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topics:
      notifications: account-notifications

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,prometheus,traces
  
  # Tracing configuration
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_RATE:1.0}
  
  # Zipkin exporter configuration
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://bankapp-zipkin:9411}/api/v2/spans

logging:
  level:
    ru.rpovetkin.notifications: INFO
    org.springframework.kafka: INFO
    org.springframework.messaging: INFO
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
