spring:
  application:
    name: exchange
  config:
    import: optional:consul:
  cloud:
    compatibility-verifier:
      enabled: false
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: application
        data-key: data
        watch:
          enabled: true
      discovery:
        enabled: ${SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED:true}
        register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
        service-name: ${SPRING_CLOUD_CONSUL_DISCOVERY_SERVICE_NAME:exchange}
        instance-id: ${SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ID:exchange-${random.uuid}}
        hostname: exchange-app
        health-check-path: /actuator/health
        health-check-interval: 15s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,refresh

logging:
  level:
    ru.rpovetkin.exchange: DEBUG
    org.springframework.security: DEBUG