spring:
  application:
    name: exchange
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}

server:
  port: 8084

logging:
  level:
    ru.rpovetkin.exchange: DEBUG
    org.springframework.security: DEBUG