spring:
  application:
    name: exchange
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: exchange-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 1
    topics:
      exchange-rates: exchange-rates

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}

oauth2:
  client:
    id: ${OAUTH2_CLIENT_ID:exchange-service}
    secret: ${OAUTH2_CLIENT_SECRET:exchange-secret-key-12345}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,refresh

logging:
  level:
    ru.rpovetkin.exchange: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG