apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}
  labels:
    {{- include "consul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8500
      protocol: TCP
      name: http
    - port: {{ .Values.service.dnsPort }}
      targetPort: 8600
      protocol: UDP
      name: dns
  selector:
    {{- include "consul.selectorLabels" . | nindent 4 }}


